import Blog from './Blog'
import Brands from './Brands'
import CtaSection from './CtaSection'
import Hero from './Hero'
import Newsletter from './Newsletter'
import Services from './Services'
import Skills from './Skills'
import Stats from './Stats'
import Team from './Team'
import Testimonials from './Testimonials'
import WhyChooseUs from './WhyChooseUs'
import WhyTrustUs from './WhyTrustUs'

export { Blog }
export { Brands }
export { CtaSection }
export { Hero }
export { Newsletter }
export { Services }
export { Skills }
export { Stats }
export { Team }
export { Testimonials }
export { WhyChooseUs }
export { WhyTrustUs }
